//
// Created by matia on 22-11-2023.
//

#ifndef P1_PROJECT_MINEFIELD_PATHFINDING_READ_PRINT_TERRAIN_MAP_H
#define P1_PROJECT_MINEFIELD_PATHFINDING_READ_PRINT_TERRAIN_MAP_H

int read_print_terrainmap();

#endif //P1_PROJECT_MINEFIELD_PATHFINDING_READ_PRINT_TERRAIN_MAP_H

