// Tile
#define SETTINGS_TILE_COST 5

// Landmine
#define SETTINGS_LANDMINE_COST 69
#define SETTINGS_LANDMINE_BANDWIDTH 1

// Start and target tile
#define START_X 20
#define START_Y 5
#define TARGET_X 27
#define TARGET_Y 50

// Terrain
#define SETTINGS_TERRAIN_HILL_COST 5
#define SETTINGS_TERRAIN_ROAD_COST 1
#define SETTINGS_TERRAIN_FIELD_COST 3
#define SETTINGS_TERRAIN_RIVER_COST 8
#define SETTINGS_TERRAIN_FOREST_COST 7

// Economic valuation
#define GDP_SCALE_FACTOR 1 // Scale factor when computing the growth generated by linking two cities.
#define DISCOUNT_RATE 0.95 // Money in the future is worth less than money now.
#define EXPECTED_GROWTH 1.02 // How much do we expect the economy to grow?
#define LOOK_FORWARD_YEARS 25 // How long do we look forward when evaluation economic gain?
#define ROAD_MAINTENANCE_COST 10 // How much a km of road will cost to maintain per year.
#define TILE_LENGTH_CONVERSION 10 // How many km long is the side of a tile?