// Tile
#define SETTINGS_TILE_COST 5

// Landmine
#define SETTINGS_LANDMINE_COST 69
#define SETTINGS_LANDMINE_BANDWIDTH 1

// Terrain
#define SETTINGS_TERRAIN_HILL_COST 5
#define SETTINGS_TERRAIN_ROAD_COST 1
#define SETTINGS_TERRAIN_FIELD_COST 3
#define SETTINGS_TERRAIN_RIVER_COST 8
#define SETTINGS_TERRAIN_FOREST_COST 7
